function dual_fivebar_plot( ...
    simTime, ...
    alphaL, betaL, xL, yL, lenL, angL, validL, ...
    alphaR, betaR, xR, yR, lenR, angR, validR, ...
    L1, L4, L5, ...
    xTargetL, yTargetL, xTargetR, yTargetR)
% dual_fivebar_plot
% 双腿五连杆实际状态动画，并显示左右足端目标点
%
% 仅用于 Simulink Normal 模式可视化，不参与控制。
%
% 输入单位：
%   alpha、beta、ang：rad
%   x、y、len、L1、L4、L5、Target：m
%
% 坐标系：
%   +x：Alpha电机指向Beta电机
%   +y：竖直向下
%
% 显示说明：
%   原有轮毂圆点：实际足端位置
%   蓝色空心大圆：目标足端位置

%% 持久变量

persistent fig axL axR

persistent hLinksL hJointsL hWheelL hInfoL hTargetL
persistent hLinksR hJointsR hWheelR hInfoR hTargetR

persistent lastDrawTime

%% 动画刷新周期

refreshPeriod = 0.05;  % 20 FPS

if isempty(lastDrawTime)
    lastDrawTime = -inf;
end

% 仿真重新开始
if simTime < lastDrawTime
    lastDrawTime = -inf;
end

% 尚未到下一次刷新时间
if simTime - lastDrawTime < refreshPeriod
    return;
end

lastDrawTime = simTime;

%% 判断是否需要重新创建窗口

needCreateFigure = ...
    isempty(fig) || ...
    ~isgraphics(fig) || ...
    isempty(axL) || ...
    ~isgraphics(axL) || ...
    isempty(axR) || ...
    ~isgraphics(axR) || ...
    isempty(hTargetL) || ...
    ~isgraphics(hTargetL) || ...
    isempty(hTargetR) || ...
    ~isgraphics(hTargetR);

%% 创建窗口

if needCreateFigure

    fig = figure( ...
        'Name', 'Left and Right Five-Bar Actual Kinematics', ...
        'NumberTitle', 'off', ...
        'MenuBar', 'figure', ...
        'ToolBar', 'figure', ...
        'Position', [100, 100, 1250, 650], ...
        'Color', 'white');

    layout = tiledlayout(fig, 1, 2, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    %% =====================================================
    % 左腿坐标轴
    % ======================================================

    axL = nexttile(layout, 1);

    hold(axL, 'on');
    grid(axL, 'on');
    axis(axL, 'equal');

    set(axL, ...
        'YDir', 'reverse', ...
        'FontSize', 10);

    xlabel(axL, 'x / m');
    ylabel(axL, 'y / m');

    xlim(axL, [-0.12, 0.23]);
    ylim(axL, [-0.04, 0.27]);

    title(axL, 'LEFT LEG', ...
        'FontSize', 14, ...
        'FontWeight', 'bold');

    % 五连杆线
    hLinksL = plot(axL, ...
        nan, nan, ...
        '-', ...
        'LineWidth', 3);

    % 五个关节点
    hJointsL = plot(axL, ...
        nan, nan, ...
        'o', ...
        'MarkerSize', 8, ...
        'LineWidth', 2);

    % 轮毂中心，即实际足端位置
    hWheelL = plot(axL, ...
        nan, nan, ...
        'o', ...
        'MarkerSize', 15, ...
        'LineWidth', 3);

    % 新增：左腿目标足端位置
    % 使用大号蓝色空心圆，避免与实际点完全重合时被遮挡
    hTargetL = plot(axL, ...
        nan, nan, ...
        'bo', ...
        'MarkerSize', 20, ...
        'LineWidth', 2.5, ...
        'MarkerFaceColor', 'none');

    % 左腿实时信息框：右下角
    hInfoL = text(axL, ...
        0.98, 0.02, '', ...
        'Units', 'normalized', ...
        'VerticalAlignment', 'bottom', ...
        'HorizontalAlignment', 'right', ...
        'FontName', 'Monospaced', ...
        'FontSize', 10, ...
        'Interpreter', 'none', ...
        'BackgroundColor', 'white', ...
        'EdgeColor', [0.45, 0.45, 0.45], ...
        'Margin', 6, ...
        'Clipping', 'on');

    %% =====================================================
    % 右腿坐标轴
    % ======================================================

    axR = nexttile(layout, 2);

    hold(axR, 'on');
    grid(axR, 'on');
    axis(axR, 'equal');

    set(axR, ...
        'YDir', 'reverse', ...
        'FontSize', 10);

    xlabel(axR, 'x / m');
    ylabel(axR, 'y / m');

    xlim(axR, [-0.12, 0.23]);
    ylim(axR, [-0.04, 0.27]);

    title(axR, 'RIGHT LEG', ...
        'FontSize', 14, ...
        'FontWeight', 'bold');

    hLinksR = plot(axR, ...
        nan, nan, ...
        '-', ...
        'LineWidth', 3);

    hJointsR = plot(axR, ...
        nan, nan, ...
        'o', ...
        'MarkerSize', 8, ...
        'LineWidth', 2);

    % 轮毂中心，即实际足端位置
    hWheelR = plot(axR, ...
        nan, nan, ...
        'o', ...
        'MarkerSize', 15, ...
        'LineWidth', 3);

    % 新增：右腿目标足端位置
    hTargetR = plot(axR, ...
        nan, nan, ...
        'bo', ...
        'MarkerSize', 20, ...
        'LineWidth', 2.5, ...
        'MarkerFaceColor', 'none');

    % 右腿实时信息框：右下角
    hInfoR = text(axR, ...
        0.98, 0.02, '', ...
        'Units', 'normalized', ...
        'VerticalAlignment', 'bottom', ...
        'HorizontalAlignment', 'right', ...
        'FontName', 'Monospaced', ...
        'FontSize', 10, ...
        'Interpreter', 'none', ...
        'BackgroundColor', 'white', ...
        'EdgeColor', [0.45, 0.45, 0.45], ...
        'Margin', 6, ...
        'Clipping', 'on');
end

%% =========================================================
% 更新目标点
% ==========================================================

leftTargetValid = ...
    isfinite(xTargetL) && ...
    isfinite(yTargetL);

rightTargetValid = ...
    isfinite(xTargetR) && ...
    isfinite(yTargetR);

if leftTargetValid

    set(hTargetL, ...
        'XData', xTargetL, ...
        'YData', yTargetL);

else

    set(hTargetL, ...
        'XData', nan, ...
        'YData', nan);
end

if rightTargetValid

    set(hTargetR, ...
        'XData', xTargetR, ...
        'YData', yTargetR);

else

    set(hTargetR, ...
        'XData', nan, ...
        'YData', nan);
end

%% =========================================================
% 左腿绘制
% ==========================================================

leftDataValid = ...
    logical(validL) && ...
    all(isfinite([alphaL, betaL, xL, yL, lenL, angL]));

if leftDataValid

    % 主动杆末端A
    AxL = L1 * cos(alphaL);
    AyL = L1 * sin(alphaL);

    % 主动杆末端C
    CxL = L5 + L4 * cos(betaL);
    CyL = L4 * sin(betaL);

    % 闭环五连杆：O → A → B → C → D → O
    set(hLinksL, ...
        'XData', [0, AxL, xL, CxL, L5, 0], ...
        'YData', [0, AyL, yL, CyL, 0, 0]);

    % 五个关节点：O、A、B、C、D
    set(hJointsL, ...
        'XData', [0, AxL, xL, CxL, L5], ...
        'YData', [0, AyL, yL, CyL, 0]);

    % 轮毂中心B
    set(hWheelL, ...
        'XData', xL, ...
        'YData', yL);

    leftInfo = sprintf([ ...
        'alpha     = %8.2f deg\n', ...
        'beta      = %8.2f deg\n', ...
        'wheel x   = %8.1f mm\n', ...
        'wheel y   = %8.1f mm\n', ...
        'leg len   = %8.1f mm\n', ...
        'leg angle = %8.2f deg'], ...
        alphaL * 180 / pi, ...
        betaL  * 180 / pi, ...
        xL     * 1000, ...
        yL     * 1000, ...
        lenL   * 1000, ...
        angL   * 180 / pi);

    set(hInfoL, ...
        'String', leftInfo, ...
        'BackgroundColor', 'white', ...
        'EdgeColor', [0.45, 0.45, 0.45]);

else

    % 清除旧姿态，避免无效时仍显示上一帧
    set(hLinksL, ...
        'XData', nan, ...
        'YData', nan);

    set(hJointsL, ...
        'XData', nan, ...
        'YData', nan);

    set(hWheelL, ...
        'XData', nan, ...
        'YData', nan);

    leftInvalidInfo = sprintf([ ...
        'KINEMATICS INVALID\n', ...
        'Check motor feedback,\n', ...
        'calibration and linkage']);

    set(hInfoL, ...
        'String', leftInvalidInfo, ...
        'BackgroundColor', [1.0, 0.90, 0.90], ...
        'EdgeColor', [0.75, 0.20, 0.20]);
end

%% =========================================================
% 右腿绘制
% ==========================================================

rightDataValid = ...
    logical(validR) && ...
    all(isfinite([alphaR, betaR, xR, yR, lenR, angR]));

if rightDataValid

    AxR = L1 * cos(alphaR);
    AyR = L1 * sin(alphaR);

    CxR = L5 + L4 * cos(betaR);
    CyR = L4 * sin(betaR);

    set(hLinksR, ...
        'XData', [0, AxR, xR, CxR, L5, 0], ...
        'YData', [0, AyR, yR, CyR, 0, 0]);

    set(hJointsR, ...
        'XData', [0, AxR, xR, CxR, L5], ...
        'YData', [0, AyR, yR, CyR, 0]);

    set(hWheelR, ...
        'XData', xR, ...
        'YData', yR);

    rightInfo = sprintf([ ...
        'alpha     = %8.2f deg\n', ...
        'beta      = %8.2f deg\n', ...
        'wheel x   = %8.1f mm\n', ...
        'wheel y   = %8.1f mm\n', ...
        'leg len   = %8.1f mm\n', ...
        'leg angle = %8.2f deg'], ...
        alphaR * 180 / pi, ...
        betaR  * 180 / pi, ...
        xR     * 1000, ...
        yR     * 1000, ...
        lenR   * 1000, ...
        angR   * 180 / pi);

    set(hInfoR, ...
        'String', rightInfo, ...
        'BackgroundColor', 'white', ...
        'EdgeColor', [0.45, 0.45, 0.45]);

else

    set(hLinksR, ...
        'XData', nan, ...
        'YData', nan);

    set(hJointsR, ...
        'XData', nan, ...
        'YData', nan);

    set(hWheelR, ...
        'XData', nan, ...
        'YData', nan);

    rightInvalidInfo = sprintf([ ...
        'KINEMATICS INVALID\n', ...
        'Check motor feedback,\n', ...
        'calibration and linkage']);

    set(hInfoR, ...
        'String', rightInvalidInfo, ...
        'BackgroundColor', [1.0, 0.90, 0.90], ...
        'EdgeColor', [0.75, 0.20, 0.20]);
end

%% 刷新动画

drawnow limitrate nocallbacks;

end